# Site settings
title: My First Project
header-img: img/home-bg.png
email: heriberto@melo.nyc
copyright_name: hmelo1
description: > # this means to ignore newlines until "baseurl:"
  I Should Probably Read Instructions Beforehand
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  hmelo1
learn_profile: hmelo1
email_username: heriberto@melo.nyc

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
